//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelToSQL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelToSQL.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Files.
        /// </summary>
        internal static string AllSupportedFiles {
            get {
                return ResourceManager.GetString("AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load user settings. Defaults will be used..
        /// </summary>
        internal static string CantLoadSettings {
            get {
                return ResourceManager.GetString("CantLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Table.
        /// </summary>
        internal static string CreateTable {
            get {
                return ResourceManager.GetString("CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter:.
        /// </summary>
        internal static string Delimiter {
            get {
                return ResourceManager.GetString("Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter set to Auto. The application will attempt to detect it..
        /// </summary>
        internal static string DelimiterAuto {
            get {
                return ResourceManager.GetString("DelimiterAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not autodetect the delimiter. Please select one manually..
        /// </summary>
        internal static string DelimiterWarning {
            get {
                return ResourceManager.GetString("DelimiterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag File Here.
        /// </summary>
        internal static string DragFileHere {
            get {
                return ResourceManager.GetString("DragFileHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating SQL: .
        /// </summary>
        internal static string ErrorGeneratingSQL {
            get {
                return ResourceManager.GetString("ErrorGeneratingSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading file: .
        /// </summary>
        internal static string ErrorLoadingfile {
            get {
                return ResourceManager.GetString("ErrorLoadingfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file: .
        /// </summary>
        internal static string ErrorSavingFile {
            get {
                return ResourceManager.GetString("ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate SQL.
        /// </summary>
        internal static string GenerateSQL {
            get {
                return ResourceManager.GetString("GenerateSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data loaded. Please upload or drag a file..
        /// </summary>
        internal static string NoDataLoadedError {
            get {
                return ResourceManager.GetString("NoDataLoadedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sheet selected. Operation cancelled..
        /// </summary>
        internal static string NoSheetSelected {
            get {
                return ResourceManager.GetString("NoSheetSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation:.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Table.
        /// </summary>
        internal static string OperationCreate {
            get {
                return ResourceManager.GetString("OperationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Table.
        /// </summary>
        internal static string OperationUpdate {
            get {
                return ResourceManager.GetString("OperationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save operation cancelled..
        /// </summary>
        internal static string SaveOperationCancelled {
            get {
                return ResourceManager.GetString("SaveOperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save SQL File.
        /// </summary>
        internal static string SaveSQLFileTitle {
            get {
                return ResourceManager.GetString("SaveSQLFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sheet to process:.
        /// </summary>
        internal static string SelectSheet {
            get {
                return ResourceManager.GetString("SelectSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Sheet.
        /// </summary>
        internal static string SelectSheetTitle {
            get {
                return ResourceManager.GetString("SelectSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL file saved: .
        /// </summary>
        internal static string SQLFileSaved {
            get {
                return ResourceManager.GetString("SQLFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target SQL:.
        /// </summary>
        internal static string TargetSQL {
            get {
                return ResourceManager.GetString("TargetSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format. Please upload a CSV or Excel file..
        /// </summary>
        internal static string UnsupportedFile {
            get {
                return ResourceManager.GetString("UnsupportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Table.
        /// </summary>
        internal static string UpdateTable {
            get {
                return ResourceManager.GetString("UpdateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
    }
}
